CREATE TABLE User (
    Username VARCHAR(64),
    Password VARCHAR(64) NOT NULL,
    IsAdmin	 BOOLEAN	 NOT NULL,
    PRIMARY KEY(Username));

CREATE TABLE Passenger(
	Username VARCHAR(64),
	Email	 VARCHAR(64) NOT NULL,

	PRIMARY KEY(Username),
	FOREIGN KEY (Username) REFERENCES User(Username) ON UPDATE CASCADE
	ON DELETE CASCADE,
	UNIQUE(Email));

CREATE TABLE Breezecard(
	BreezecardNum Char(16),
	Value Decimal(6,2) NOT NULL,
	BelongsTo VARCHAR(64),
	PRIMARY KEY (BreezecardNum),
	FOREIGN KEY (BelongsTo) REFERENCES User(Username) ON DELETE SET NULL ON UPDATE CASCADE,
	CHECK(Value >= 0.0 AND Value <= 1000.00)
);

CREATE TABLE Conflict(
	Username VARCHAR(64),
	BreezecardNum CHAR(16),
	DateTime DATETIME DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(Username, BreezecardNum),
	FOREIGN KEY(Username) REFERENCES Passenger(Username) ON DELETE CASCADE ON UPDATE RESTRICT,
	FOREIGN KEY(BreezecardNum) REFERENCES Breezecard(BreezecardNum) ON DELETE RESTRICT ON UPDATE RESTRICT);

CREATE TABLE Station(
	StopID VARCHAR(16),
	Name VARCHAR(64) NOT NULL,
	EnterFare Decimal(4,2) NOT NULL,
	ClosedStatus BOOLEAN NOT NULL,
	IsTrain BOOLEAN NOT NULL,
	PRIMARY KEY(StopID),
	UNIQUE(Name, IsTrain),
	CHECK(EnterFare >= 0 AND EnterFare <= 50));

CREATE TABLE BusStation(
	StopID VARCHAR(16),
	Intersection VARCHAR(64),
	PRIMARY KEY(StopID),
	FOREIGN KEY(StopID) REFERENCES Station(StopID) ON DELETE CASCADE ON UPDATE CASCADE);


CREATE TABLE Trip(
	BreezecardNum CHAR(16),
	StartTime DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Tripfare Decimal(10,2) NOT NULL,
	StartsAt VARCHAR(16),
	EndsAt VARCHAR(16),
	PRIMARY KEY(BreezecardNum, StartTime),
	FOREIGN KEY(StartsAt) REFERENCES Station(StopID) ON DELETE SET NULL ON UPDATE SET NULL,
	FOREIGN KEY(EndsAt) REFERENCES Station(StopID) ON DELETE SET NULL ON UPDATE SET NULL,
	FOREIGN KEY(BreezecardNum) REFERENCES Breezecard(BreezecardNum) ON DELETE RESTRICT ON UPDATE RESTRICT);




